# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/park/technopark_c_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/park/technopark_c_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/park/technopark_c_cpp/CMakeFiles /mnt/c/park/technopark_c_cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/park/technopark_c_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named libs

# Build rule for target.
libs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libs
.PHONY : libs

# fast build rule for target.
libs/fast:
	$(MAKE) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/build
.PHONY : libs/fast

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.s
.PHONY : main.c.s

src/custom_errors.o: src/custom_errors.c.o

.PHONY : src/custom_errors.o

# target to build an object file
src/custom_errors.c.o:
	$(MAKE) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/custom_errors.c.o
.PHONY : src/custom_errors.c.o

src/custom_errors.i: src/custom_errors.c.i

.PHONY : src/custom_errors.i

# target to preprocess a source file
src/custom_errors.c.i:
	$(MAKE) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/custom_errors.c.i
.PHONY : src/custom_errors.c.i

src/custom_errors.s: src/custom_errors.c.s

.PHONY : src/custom_errors.s

# target to generate assembly for a file
src/custom_errors.c.s:
	$(MAKE) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/custom_errors.c.s
.PHONY : src/custom_errors.c.s

src/data.o: src/data.c.o

.PHONY : src/data.o

# target to build an object file
src/data.c.o:
	$(MAKE) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/data.c.o
.PHONY : src/data.c.o

src/data.i: src/data.c.i

.PHONY : src/data.i

# target to preprocess a source file
src/data.c.i:
	$(MAKE) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/data.c.i
.PHONY : src/data.c.i

src/data.s: src/data.c.s

.PHONY : src/data.s

# target to generate assembly for a file
src/data.c.s:
	$(MAKE) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/data.c.s
.PHONY : src/data.c.s

src/io.o: src/io.c.o

.PHONY : src/io.o

# target to build an object file
src/io.c.o:
	$(MAKE) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/io.c.o
.PHONY : src/io.c.o

src/io.i: src/io.c.i

.PHONY : src/io.i

# target to preprocess a source file
src/io.c.i:
	$(MAKE) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/io.c.i
.PHONY : src/io.c.i

src/io.s: src/io.c.s

.PHONY : src/io.s

# target to generate assembly for a file
src/io.c.s:
	$(MAKE) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/io.c.s
.PHONY : src/io.c.s

src/list.o: src/list.c.o

.PHONY : src/list.o

# target to build an object file
src/list.c.o:
	$(MAKE) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/list.c.o
.PHONY : src/list.c.o

src/list.i: src/list.c.i

.PHONY : src/list.i

# target to preprocess a source file
src/list.c.i:
	$(MAKE) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/list.c.i
.PHONY : src/list.c.i

src/list.s: src/list.c.s

.PHONY : src/list.s

# target to generate assembly for a file
src/list.c.s:
	$(MAKE) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/list.c.s
.PHONY : src/list.c.s

test/test_custom_errors.o: test/test_custom_errors.cpp.o

.PHONY : test/test_custom_errors.o

# target to build an object file
test/test_custom_errors.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_custom_errors.cpp.o
.PHONY : test/test_custom_errors.cpp.o

test/test_custom_errors.i: test/test_custom_errors.cpp.i

.PHONY : test/test_custom_errors.i

# target to preprocess a source file
test/test_custom_errors.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_custom_errors.cpp.i
.PHONY : test/test_custom_errors.cpp.i

test/test_custom_errors.s: test/test_custom_errors.cpp.s

.PHONY : test/test_custom_errors.s

# target to generate assembly for a file
test/test_custom_errors.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_custom_errors.cpp.s
.PHONY : test/test_custom_errors.cpp.s

test/test_data.o: test/test_data.cpp.o

.PHONY : test/test_data.o

# target to build an object file
test/test_data.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_data.cpp.o
.PHONY : test/test_data.cpp.o

test/test_data.i: test/test_data.cpp.i

.PHONY : test/test_data.i

# target to preprocess a source file
test/test_data.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_data.cpp.i
.PHONY : test/test_data.cpp.i

test/test_data.s: test/test_data.cpp.s

.PHONY : test/test_data.s

# target to generate assembly for a file
test/test_data.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_data.cpp.s
.PHONY : test/test_data.cpp.s

test/test_io.o: test/test_io.cpp.o

.PHONY : test/test_io.o

# target to build an object file
test/test_io.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_io.cpp.o
.PHONY : test/test_io.cpp.o

test/test_io.i: test/test_io.cpp.i

.PHONY : test/test_io.i

# target to preprocess a source file
test/test_io.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_io.cpp.i
.PHONY : test/test_io.cpp.i

test/test_io.s: test/test_io.cpp.s

.PHONY : test/test_io.s

# target to generate assembly for a file
test/test_io.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_io.cpp.s
.PHONY : test/test_io.cpp.s

test/test_list.o: test/test_list.cpp.o

.PHONY : test/test_list.o

# target to build an object file
test/test_list.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_list.cpp.o
.PHONY : test/test_list.cpp.o

test/test_list.i: test/test_list.cpp.i

.PHONY : test/test_list.i

# target to preprocess a source file
test/test_list.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_list.cpp.i
.PHONY : test/test_list.cpp.i

test/test_list.s: test/test_list.cpp.s

.PHONY : test/test_list.s

# target to generate assembly for a file
test/test_list.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_list.cpp.s
.PHONY : test/test_list.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... tests"
	@echo "... libs"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/custom_errors.o"
	@echo "... src/custom_errors.i"
	@echo "... src/custom_errors.s"
	@echo "... src/data.o"
	@echo "... src/data.i"
	@echo "... src/data.s"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... test/test_custom_errors.o"
	@echo "... test/test_custom_errors.i"
	@echo "... test/test_custom_errors.s"
	@echo "... test/test_data.o"
	@echo "... test/test_data.i"
	@echo "... test/test_data.s"
	@echo "... test/test_io.o"
	@echo "... test/test_io.i"
	@echo "... test/test_io.s"
	@echo "... test/test_list.o"
	@echo "... test/test_list.i"
	@echo "... test/test_list.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

